version: '3'
services:

  postgres:
    image: postgres
    hostname: postgres
    ports:
      - "6543:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: kouyi_palm_treasure
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  api-server:
    container_name: api-server
    build:
      dockerfile: ./docker/api-server/Dockerfile
      context: .
    ports:
      - "8282:8282"
    restart: always
    depends_on:
      - postgres
    links:
      - postgres

  document:
    container_name: document
    build:
      context: .
      dockerfile: ./docker/document/Dockerfile
    environment:
      API_URL: swagger/openapi.yaml
    ports:
      - '8080:8080'
    volumes:
      - ./document:/usr/share/nginx/html/swagger

  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    restart: always
    ports:
      - "80:80"
    depends_on:
      - api-server
volumes:
  postgres-data:
