url:      'https://www.topigeon.com.tw/index.asp?Page=1&QSite=&QSysid=2108&QRaceDate=2022%2F07%2F17&QSort=0&QSiteCode=&QMode=race&qsize=1000&p=N&QPass='
urlf:     'https://www.11568.com.tw/index.asp?Page='
urlb:     '&QSite=&QSysid=2108&QRaceDate=2022%2F07%2F17&QSort=0&QSiteCode=&QMode=race&qsize=1000&p=N&QPass='
areacode: 06
koipc:    A4
status:   01
day:      '2022-07-17'