url:          http://60.248.233.195:86/
sID:          wtph
sPW:          3678
sType:        R
verCode:      Rex2022KouYi
areacode:     02
koipc:        A23
status:       01
startfrom:    1
loftdigit:    4